# Generated by Django 4.1.7 on 2023-04-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercera_pre_entrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_caption_title', models.CharField(max_length=30)),
                ('carousel_caption_description', models.CharField(max_length=80)),
                ('heading', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='nombre',
            new_name='tipo',
        ),
    ]
