# Generated by Django 4.1.7 on 2023-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercera_pre_entrega', '0004_usuario_usuario_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.TextField(max_length=100)),
                ('tipo', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
